/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import Datos.ConexionBaseDatos;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Admie21
 */
public class Login extends javax.swing.JFrame {

    ConexionBaseDatos conexion = new ConexionBaseDatos();
    
    private Connection connection = null;
    private ResultSet rs = null;
    private Statement s = null;
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void conexionParaLogin() {
        if (connection != null) {
            return;
        }

        String nombreBaseDatos="prueba";//aqui va el nombre de la base de datos 
        String url = "jdbc:postgresql://localhost:5433/"+nombreBaseDatos;//este es el nombre de la base de datos
        String password = "Saborio17";//esta es la contraseña del postgrade deñ usuario
        try {
            Class.forName("org.postgresql.Driver");
            connection = DriverManager.getConnection(url,"postgres", password);//este es el nombre sel server
            if (connection != null) {
                System.out.println("Connecting to database... Base Datos Conectada "+nombreBaseDatos);
            }
        } catch (Exception e) {
            System.out.println("Problem when connecting to the database... No se Puede conectar la Base Datos "+nombreBaseDatos);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuarioCedula = new javax.swing.JTextField();
        btnInicioSesion = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario Cedula");

        jLabel2.setText("Contraseña");

        btnInicioSesion.setText("Iniciar Sesion");
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });
        btnInicioSesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnInicioSesionKeyPressed(evt);
            }
        });

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        txtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraseñaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuarioCedula)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnInicioSesion)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuarioCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(btnInicioSesion)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
        // TODO add your handling code here:
        
       //conexion.conexionParaLogin();
     
       conexionParaLogin();
       
        try {
            String cedulaConsulta = txtUsuarioCedula.getText();
            String contraseñaConsulta=txtContraseña.getText();
            
            s = connection.createStatement();
            rs = s.executeQuery("SELECT * FROM usuarios_registrados WHERE usuario_cedula = '" + cedulaConsulta + "'");

            while (rs.next()) {
             
                
                String cedulaDB= rs.getString("usuario_cedula");
                
                if(cedulaDB.equals(cedulaConsulta) ){
                
                    JOptionPane.showMessageDialog(null,"Welcome Roger");
                    System.out.println("estas registrado en el sistema");
                }
                if(!cedulaDB.equals(cedulaConsulta))
                {
                JOptionPane.showMessageDialog(null,"Incorrect Password");
                    System.out.println("no estas registrado en el sistema");
                }
                
            }
        } catch (Exception e) {
            System.out.println("Error de conexión No conecta la DB");
        }
        
        
    }//GEN-LAST:event_btnInicioSesionActionPerformed

    private void btnInicioSesionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnInicioSesionKeyPressed
        // TODO add your handling code here:
        
        conexionParaLogin();
       
        try {
            String cedulaConsulta = txtUsuarioCedula.getText();
            String contraseñaConsulta=txtContraseña.getText();
            
            s = connection.createStatement();
            rs = s.executeQuery("SELECT * FROM usuarios_registrados WHERE usuario_cedula = '" + cedulaConsulta + "'");

            while (rs.next()) {
             
                
                String cedulaDB= rs.getString("usuario_cedula");
                
                if(cedulaDB.equals(cedulaConsulta) ){
                
                    JOptionPane.showMessageDialog(null,"Welcome Roger");
                    System.out.println("estas registrado en el sistema");
                }
                if(!cedulaDB.equals(cedulaConsulta))
                {
                JOptionPane.showMessageDialog(null,"Incorrect Password");
                    System.out.println("no estas registrado en el sistema");
                }
                
            }
        } catch (Exception e) {
            System.out.println("Error de conexión No conecta la DB");
        }
        
    }//GEN-LAST:event_btnInicioSesionKeyPressed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void txtContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        
             conexionParaLogin();
       
        try {
            String cedulaConsulta = txtUsuarioCedula.getText();
            String contraseñaConsulta=txtContraseña.getText();
            
            s = connection.createStatement();
            rs = s.executeQuery("SELECT * FROM usuarios_registrados WHERE usuario_cedula = '" + cedulaConsulta + "'");

            while (rs.next()) {
             
                
                String cedulaDB= rs.getString("usuario_cedula");
                
                if(cedulaDB.equals(cedulaConsulta) ){
                
                    JOptionPane.showMessageDialog(null,"Welcome Roger");
                    System.out.println("estas registrado en el sistema");
                }
                if(!cedulaDB.equals(cedulaConsulta))
                {
                JOptionPane.showMessageDialog(null,"Incorrect Password");
                    System.out.println("no estas registrado en el sistema");
                }
                
            }
        } catch (Exception e) {
            System.out.println("Error de conexión No conecta la DB");
        }
        
        
        }
    }//GEN-LAST:event_txtContraseñaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicioSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuarioCedula;
    // End of variables declaration//GEN-END:variables
}
